### ISSUE TITLE
static null injector

### ISSUE THREAD

**Issue by rajhim** [supply-chain-ventures/angular-pdfmake#1]
core.js:1350 ERROR Error: Uncaught (in promise): Error: StaticInjectorError[InjectionToken LocaleId]: 
  StaticInjectorError[InjectionToken LocaleId]: 
    NullInjectorError: No provider for InjectionToken LocaleId!
Error: StaticInjectorError[InjectionToken LocaleId]: 
  StaticInjectorError[InjectionToken LocaleId]: 
    NullInjectorError: No provider for InjectionToken LocaleId!

**Comment by gfigueroa** [comment]
Thank you for reporting this error. Can you please indicate when and how this error appears?
Kind regards,

Gerardo O. Figueroa
    On Thursday, July 26, 2018, 6:07:41 AM GMT+2, Rajhim Shahi <notifications@github.com> wrote:  
 
 
core.js:1350 ERROR Error: Uncaught (in promise): Error: StaticInjectorError[InjectionToken LocaleId]:
StaticInjectorError[InjectionToken LocaleId]:
NullInjectorError: No provider for InjectionToken LocaleId!
Error: StaticInjectorError[InjectionToken LocaleId]:
StaticInjectorError[InjectionToken LocaleId]:
NullInjectorError: No provider for InjectionToken LocaleId!
